### ISSUE TITLE
appid，appsecret 配置在哪里

### ISSUE THREAD

**Issue by yccjack** [8Q757/API-Signed#1]
appid，appsecret 配置在哪里

**Comment by 8Q757** [comment]
默认实现是使用redis作为缓存，[MyApplicationRunner](https://github.com/veneris/API-Signed/blob/dev/example/src/main/java/cn/oever/example/init/MyApplicationRunner.java)给出的demo是项目启动时候将一组`appId`,`appSecret`set进了redis中。
更好的做法是，可以将多组`appId`,`appSecret`保存在数据库中，启动时候全部查询并set到redis中。

**Comment by yccjack** [comment]
谢谢
